// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctdwqdhetlyewdekwghw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0ZHdxZGhldGx5ZXdkZWt3Z2h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3NzYwNjIsImV4cCI6MjA1MTM1MjA2Mn0.hgQbLKIItrI_1-rikAXMrhSfU5pWpkZEW9DYayle5SE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);